parameters:
  security.firewall.name: "secured_area"
  oxygen.userbundle.from.email: test@test.com
  oxygen.userextensionbundle.name: "OxygenUserExtensionBundle"
  oxygen.userextensionbundle.namespace: "Oxygen\\UserExtensionBundle\\Entity\\User"
